/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// It's auto-generated by Next.js
// It's required for proper TypeScript support in Next.js 